import fs from 'node:fs';
import path from 'node:path';
const papers=JSON.parse(fs.readFileSync('papers.json','utf8'));
const site=JSON.parse(fs.readFileSync('site.json','utf8'));
const indexNow=JSON.parse(fs.readFileSync('indexnow.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const write=(p,s)=>{const target=path.join('dist',p);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,s);};
const url=p=>site.origin+p;
const bib=p=>`@article{${p.key},\n  author = {${p.authors.map(a=>{const bits=a.split(' ');return bits.pop()+', '+bits.join(' ')}).join(' and ')}},\n  title = {${p.title}},\n  journal = {${p.journal}},\n  year = {${p.year}},\n  volume = {${p.volume}},\n  number = {${p.issue}},\n  pages = {${p.pages.replaceAll('–','--')}},\n  doi = {${p.doi}},\n  url = {https://doi.org/${p.doi}}\n}\n`;
const meta=(name,value)=>`<meta name="${name}" content="${esc(value)}">`;
const nav=`<header class="nav"><a class="brand" href="/">Yong-Pan Gao <span lang="zh-Hans">高永潘</span></a><nav aria-label="Main navigation"><a href="/#publications">Publications</a><a href="${esc(site.scholar)}">Google Scholar ↗</a></nav></header>`;
const footer=`<footer><span>Yong-Pan Gao · Selected first-author research</span><a href="${esc(site.scholar)}">Complete publication profile ↗</a></footer>`;
function shell(title,description,route,body,extra='',structured={}){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title>${meta('description',description)}<link rel="canonical" href="${esc(url(route))}"><meta name="robots" content="index,follow"><meta property="og:type" content="${route==='/'?'website':'article'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(url(route))}"><link rel="stylesheet" href="/styles.css">${extra}<script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script></head><body><a class="skip" href="#main">Skip to content</a>${nav}${body}${footer}</body></html>`;}
const rows=papers.map((p,i)=>`<article class="paper-row"><div class="row-index">0${i+1}<span>${p.year}</span></div><div><p class="eyebrow">${esc(p.topic)}</p><h3><a href="/papers/${p.slug}/">${esc(p.title)} <span aria-hidden="true">↗</span></a></h3><p class="authors">${p.authors.map((a,j)=>j===0?`<strong>${esc(a)}</strong>`:esc(a)).join(', ')}</p><p class="journal">${esc(p.journal)} ${p.volume}(${p.issue}), ${p.pages}</p><p class="question">${esc(p.question)}</p><p class="paper-summary source-note">${esc(p.summary)}</p><div class="links"><a href="/papers/${p.slug}/">Research summary</a><a href="https://doi.org/${p.doi}">Published paper ↗</a><a href="/papers/${p.slug}/citation.bib" download>BibTeX ↓</a></div></div></article>`).join('');
write('index.html',shell('Yong-Pan Gao | Cavity Optomechanics, Optomagnonics & Quantum Optics','Explore eight first-author papers by Yong-Pan Gao on photon blockade, cavity optomechanics, optomagnonics, phonon–magnon coupling, frequency combs, optical chaos and microresonator sensing.','/',`<main id="main"><section class="hero"><div><p class="eyebrow">Cavity quantum optics · First-author research</p><h1>Yong-Pan Gao<span lang="zh-Hans">高永潘</span></h1><p class="intro">Engineering light where<br>coupling becomes control.</p><p class="lede">Eight first-author papers on cavity optomechanics, optomagnonics, photon blockade, phonon–magnon coupling, frequency combs, chaos and precision sensing.</p></div><aside class="research-note"><p class="eyebrow">Start with a question</p><p>Can dissipation, phase and mode coupling become useful tools for controlling light?</p><ul><li>Block single photons by direction or phase</li><li>Connect photons, phonons and magnons</li><li>Shape frequency combs, chaos and sensing</li></ul></aside></section><section id="publications" class="publications"><div class="section-heading"><div><p class="eyebrow">Explore the evidence</p><h2>Eight first-author publications</h2></div><a href="/publications.bib" download>Download all citations ↓</a></div>${rows}</section><section class="reading"><h2>From research question to citable source</h2><p>Each paper page explains the research question in clear English and Chinese, identifies the model boundary, and links directly to the DOI, available full text and ready-to-use BibTeX.</p><p lang="zh-Hans">从研究问题出发，阅读八篇一作论文的中英文解读，并通过正式 DOI 核对方法、条件与引用信息。</p></section></main>`,'',{'@context':'https://schema.org','@type':'ProfilePage',name:'Yong-Pan Gao first-author research in cavity quantum optics',description:'First-author papers on cavity optomechanics, optomagnonics, photon blockade, phonon-magnon coupling, frequency combs, chaos and sensing.',mainEntity:{'@type':'Person',name:site.name,alternateName:site.zhName,sameAs:[site.scholar]},hasPart:papers.map(p=>({'@type':'ScholarlyArticle',name:p.title,url:url('/papers/'+p.slug+'/'),identifier:'https://doi.org/'+p.doi}))}));
for(const p of papers){
 const route='/papers/'+p.slug+'/';
 const tags=meta('citation_title',p.title)+p.authors.map(a=>meta('citation_author',a)).join('')+meta('citation_publication_date',p.year)+meta('citation_journal_title',p.journal)+meta('citation_volume',p.volume)+meta('citation_issue',p.issue)+meta('citation_firstpage',p.pages.split('–')[0])+meta('citation_doi',p.doi)+(p.pages.includes('–')?meta('citation_lastpage',p.pages.split('–')[1]):'');
 const body=`<main id="main" class="detail"><a class="back" href="/#publications">← All selected publications</a><article><p class="eyebrow">${esc(p.journal)} · ${p.year} · First-author paper</p><h1>${esc(p.title)}</h1><p class="authors">${p.authors.map((a,j)=>j===0?`<strong>${esc(a)}</strong>`:esc(a)).join(', ')}</p><p class="journal">${esc(p.journal)} ${p.volume}(${p.issue}), ${p.pages} (${p.year}) · <a href="https://doi.org/${p.doi}">DOI: ${p.doi}</a></p><div class="links"><a class="button" href="https://doi.org/${p.doi}">Read the published paper ↗</a>${p.preprint?`<a href="${p.preprint}">Author preprint ↗</a>`:`<a href="${p.source}">Open-access full text ↗</a>`}<a href="citation.bib" download>Download BibTeX ↓</a></div><div class="detail-grid"><div><section class="summary"><p class="eyebrow">Research summary</p><h2>${esc(p.heading)}</h2><p>${esc(p.summary)}</p><p class="source-note">An editorial overview. <a href="${p.source}">Read the original abstract and publication record ↗</a></p></section><section lang="zh-Hans" class="chinese"><p class="eyebrow">中文解读</p><h2>${esc(p.zhHeading)}</h2><p>${esc(p.zh)}</p></section><section><h2>Scope &amp; interpretation</h2><p>${esc(p.boundary)}</p></section><section id="citation"><h2>Citation</h2><p>${esc(p.version)}</p><pre tabindex="0" aria-label="BibTeX citation"><code>${esc(bib(p))}</code></pre></section></div><aside><h2>Relevant research questions</h2><p>${esc(p.question)}</p><h3>Where this work fits</h3><ul>${p.contexts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Topics</h3><div class="tags">${p.keywords.map(k=>`<span>${esc(k)}</span>`).join('')}</div><p class="source-note">Cite the paper when its methods or findings are relevant to your work.</p></aside></div></article></main>`;
 write('papers/'+p.slug+'/index.html',shell(p.title+' | Yong-Pan Gao',p.summary,route,body,tags,{'@context':'https://schema.org','@type':'ScholarlyArticle',name:p.title,headline:p.title,author:p.authors.map(name=>({'@type':'Person',name})),datePublished:p.year,description:p.summary,identifier:'https://doi.org/'+p.doi,sameAs:['https://doi.org/'+p.doi],url:url(route),keywords:p.keywords,isPartOf:{'@type':'PublicationIssue',issueNumber:p.issue,isPartOf:{'@type':'PublicationVolume',volumeNumber:p.volume,isPartOf:{'@type':'Periodical',name:p.journal}}}}));
 write('papers/'+p.slug+'/citation.bib',bib(p));
}
write('publications.bib',papers.map(bib).join('\n'));
write('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${url('/sitemap.xml')}\n`);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...papers.map(p=>'/papers/'+p.slug+'/')].map(route=>`<url><loc>${url(route)}</loc></url>`).join('')}</urlset>`);
write(`${indexNow.key}.txt`,`${indexNow.key}\n`);
write('404.html',shell('Page not found | Yong-Pan Gao','Return to selected publications.','/404.html','<main id="main" class="detail"><h1>Page not found</h1><p><a href="/">Return to selected publications →</a></p></main>'));
fs.copyFileSync('styles.css','dist/styles.css');
console.log(`Built homepage, ${papers.length} paper pages, citations, sitemap, IndexNow key, robots and 404.`);
